/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "resend.webhook": [],
    "home": [],
    "dashboard": [],
    "checkout": [],
    "orden.confirmacion": [],
    "productos": [],
    "producto.savia": [],
    "productos.categoria": [
        {
            "name": "categoria",
            "required": true
        }
    ],
    "about": [],
    "contact": [],
    "components-preview": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "admin.login": [],
    "admin.login.post": [],
    "admin.blocked": [],
    "admin.forgot-password": [],
    "admin.forgot-password.post": [],
    "admin.choose-otp-method": [],
    "admin.choose-otp-method.post": [],
    "admin.verify-otp": [],
    "admin.reset-password": [],
    "admin.reset-password.post": [],
    "admin.verify-email": [],
    "admin.verify-email.resend": [],
    "admin.invitation": [
        {
            "name": "token",
            "required": true
        }
    ],
    "admin.invitation.post": [
        {
            "name": "token",
            "required": true
        }
    ],
    "admin.dashboard": [],
    "admin.logout": [],
    "admin.usuarios.index": [],
    "admin.usuarios.store": [],
    "admin.usuarios.reenviar": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.usuarios.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.productos.index": [],
    "admin.productos.create": [],
    "admin.productos.store": [],
    "admin.productos.edit": [
        {
            "name": "producto",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.productos.update-info": [
        {
            "name": "producto",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.productos.update-precio": [
        {
            "name": "producto",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.productos.imagenes.store": [
        {
            "name": "producto",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.productos.imagenes.destroy": [
        {
            "name": "producto",
            "required": true,
            "binding": "id"
        },
        {
            "name": "imagen",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.productos.imagenes.principal": [
        {
            "name": "producto",
            "required": true,
            "binding": "id"
        },
        {
            "name": "imagen",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categorias.index": [],
    "admin.categorias.store": [],
    "admin.categorias.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categorias.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.index": [],
    "admin.roles.store": [],
    "admin.roles.toggle-permission": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
